### PR TITLE
Fix errors, make Bash compatible, and improve output format

### PR DESCRIPTION
**Pull request by xanoni**
- Clean up shellcheck warnings and add shebang
- Add bolding and enforce line width limit
- Move vars that can change to the front
- Tell user that script is not frozen
- Make the arg checking bash compatible
- Use default SAT unit spelling
- Show bullet points in output
- Show --help if an erroneous parameter is provided
- Fix calculation error in decision logic

### CODE REVIEW

**Comment by xanoni** [comment]
For context, I tried executing the script in Bash but that failed ... are you using some other shell?

Then I tried to make it Bash compatible, but got a bit extra ambitious and improved a few other things as well.

**Comment by xanoni** [comment]
By the way, I identified many of the improvements via ShellCheck ... would definitely recommend that, I have a vim plugin that automatically highlights all improvement ideas and errors.

https://github.com/koalaman/shellcheck

**Comment by xanoni** [comment]
Just realized that the script always rounded down, so I fixed that ... now it shows 1 decimal and rounds correctly.

**Comment by Czino** [comment]
Nice!, thanks for putting in the effort to improve the code and squash some bugs in the process.

I am running Raspberry Pi OS Lite. Didn't think the shell would differ that much compared to other linux distributions. Might also explain why `bc` was not installed. I tried to avoid dependencies users have to install because we better not bloat the system on a node.

If you think bc is a very common calculator tool on linux, I am going ahead and merge it.

**Comment by xanoni** [comment]
Thank you. Do you call it via `bash overview.sh`?

There was one bug in particular that should cause all recent versions of `bash` to fail:

https://github.com/Czino/lnstats/blob/0a764752880ba741abba55485dacde2e0eae8a34/overview.sh#L87-L89

There's a missing space before `]`. Here's my version (I also have Raspberry Pi):

```bash
$ bash --version
GNU bash, version 5.0.3(1)-release (arm-unknown-linux-gnueabihf)
```

Besides, another bash non-compliance I found was this:

https://github.com/Czino/lnstats/blob/0a764752880ba741abba55485dacde2e0eae8a34/overview.sh#L105-L109

`if [ false ]; then echo HELLO; fi` prints "HELLO" in bash, because the statement would always return `true`. Bash doesn't evaluate the `false` statement, it just sees that there's a non-empty string (=true). You would have to remove the square brackets for it to work as intended (which I did).

Again, most of these I found via `shellcheck` ... I really think you should give that a try, I learned a lot about Bash scripting from it.

```bash
sudo apt install shellcheck
shellcheck overview.sh
```

**Comment by xanoni** [comment]
FYI, I have `shellcheck` integrated into my `vim`, so the first thing I saw after opening the file was this warning:

image

After I fixed that, it showed me ~15 other errors, which were mostly caused by the fact that the file didn't have a Shebang (the first line that I added) ... thus it was not even clear if it's a Bash script or something lese:

image

After I added the Shebang, it knew that this was a Bash script, so it showed me the real errors etc. etc. etc. It's really useful.

**Comment by xanoni** [comment]
> If you think bc is a very common calculator tool on linux, I am going ahead and merge it.

Missed the question .... yes, I was surprised that `bc` was not part of standard Raspbian ... it's super common, I thought it was standard.

**Comment by Czino** [comment]
Awesome, will most certainly start using the shellcheck. I recently started learning shell when getting involved into lightning, so naturally I am still learning all these things.

Been running the scripts both ways: `. overview.sh` and `bash overview.sh`

Have the same version tho: 

```
bash --version
GNU bash, version 5.0.3(1)-release (arm-unknown-linux-gnueabihf)
```

Merged your code now 🎉

**Comment by xanoni** [comment]
Cool man. It's really useful to me so thank you for researching all those lncli commands for me :)

**Pull request merged**
